[package]
name = "copyd-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
num_enum = "0.7"
prost = "0.12"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
prost-build = "0.12"
